### What Is the Context?

Just as Go has a convention that the last return value from a function is an error, Go has another convention that the context is explicitly passed through your program as the first parameter of a function. The usual name for the context parameter is `ctx`:

```go
func logic(ctx context.Context, info string) (string, error) {
	// do some interesting stuff here
	return "", nil
}
```

When you don’t have an existing context, such as at the entry point to a command-line program, create an empty initial context with the function `context.Background`. This returns a variable of type `context.Context`.

`context` was added to the Go APIs long after the net/http package was created. Because of the compatibility promise, there was no way to change the http.Handler interface to add a context.Context parameter. The compatibility promise does allow new methods to be added to existing types, and that’s what the Go team did. Two context-related methods are on http.Request: 

- Context returns the context.Context associated with the request.
- WithContext takes in a context.Context and returns a new http.Request with •the old request’s state combined with the supplied context.Context.

```go
func Middleware(handler http.Handler) http.Handler {
	return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		ctx := req.Context()
		// wrap the context with stuff -- we'll see how soon!
		req = req.WithContext(ctx)
		handler.ServeHTTP(rw, req)
	})
}
```

When you implement the handler, extract the context from the request by using the Context method and call your business logic with the context as the first parameter:

```go
func handler(rw http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	err := req.ParseForm()
	if err != nil {
		rw.WriteHeader(http.StatusInternalServerError)
		rw.Write([]byte(err.Error()))
		return
	}
	data := req.FormValue("data")
	result, err := logic(ctx, data)
	if err != nil {
		rw.WriteHeader(http.StatusInternalServerError)
		rw.Write([]byte(err.Error()))
		return
	}
	rw.Write([]byte(result))
}
```

When making an HTTP call from your application to another HTTP service, use the `NewRequestWithContext` function in the `net/http` package to construct a request that includes existing context information:

```go
type ServiceCaller struct {
	client *http.Client
}

// callAnotherService shows how to add a context to an *http.Request
func (sc ServiceCaller) callAnotherService(ctx context.Context, data string) (string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		"http://example.com?data="+data, nil)
	if err != nil {
		return "", err
	}
	resp, err := sc.client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("Unexpected status code %d",
			resp.StatusCode)
	}
	// do the rest of the stuff to process the response
	id, err := processResponse(resp.Body)
	return id, err
}

// processResponse is a placeholder function for processing the body of an *http.Response
func processResponse(body io.ReadCloser) (string, error) {
	return "", nil
}
```

### Values

By default, you should prefer to pass data through explicit parameters. As has been mentioned before, idiomatic Go favors the explicit over the implicit, and this includes explicit data passing. If a function depends on some data, it should be clear what data it needs and where that data came from.

However, in some cases you cannot pass data explicitly. The most common situation is an HTTP request handler and its associated middleware. As you have seen, all HTTP request handlers have two parameters, one for the request and one for the response. If you want to make a value available to your handler in middleware, you need to store it in the context. Possible situations include extracting a user from a JWT (JSON Web Token) or creating a per-request GUID that is passed through multiple layers of middleware and into your handler and business logic.

There is a factory method for putting values into the context, context.WithValue. It takes in three values: a context, a key to look up the value, and the value itself. The key and the value parameters are declared to be of type any. The context.WithValue function returns a context, but it is not the same context that was passed into the function. Instead, it is a child context that contains the key-value pair and wraps the passed-in parent context.Context.

If no value is found for the supplied key, nil is returned. Use the comma ok idiom to type-assert the returned value to the correct type:

```go
ctx := context.Background() 
if myVal, ok := ctx.Value(myKey).(int); !ok {   
  fmt.Println("no value")
} else { 
  fmt.Println("value:", myVal)
}
```

If you are familiar with data structures, you might recognize that searching for values stored in the context chain is a **linear** search. This has no serious performance implications when there are only a few values, but it would perform poorly if you stored dozens of values in the context during a request. That said, if your program is creating a context chain with dozens of values, your program probably needs some refactoring.

The value stored in the context can be of any type, but picking the correct key is important. Like the key for a map, the key for a context value must be comparable. Don’t just use a string like "id". If you use string or another predefined or exported type for the type of the key, different packages could create identical keys, resulting in collisions. This causes problems that are hard to debug, such as one package writing data to the context that masks the data written by another package, or reading data from the context that was written by another package.

Two patterns are used to guarantee that a key is unique and comparable. The first creates a new, unexported type for the key, based on an int: 

```go
type userKey int 
```

After declaring your unexported key type, you then declare an unexported constant of that type:

```go
const (   
  _ userKey = iota   
  key 
)
```

With both the type and the typed constant of the key being unexported, no code from outside your package can put data into the context that would cause a collision.

The name of the function that creates a context with the value should start with `ContextWith`. The function that returns the value from the context should have a name that ends with `FromContext`. Here are the implementations of functions to set and read the user from the context:

```go
func ContextWithUser(ctx context.Context, user string) context.Context { 
  return context.WithValue(ctx, key, user) 
}

func UserFromContext(ctx context.Context) (string, bool) {  
  user, ok := ctx.Value(key).(string)   
  return user, ok 
}
```

Another option is to define the unexported key type by using an empty struct: 

```go
type userKey struct{}

func ContextWithUser(ctx context.Context, user string) context.Context {   
  return context.WithValue(ctx, userKey{}, user) 
}

func UserFromContext(ctx context.Context) (string, bool) { 
  user, ok := ctx.Value(userKey{}).(string)  
  return user, ok 
}
```

How do you know which key style to use? If you have a set of related keys for storing different values in the context, use the int and iota technique. If you have only a single key, either is fine. The important thing is that you want to make it impossible for context keys to collide.

You’re going to write middleware that extracts a user ID from a cookie:

```go
// a real implementation would be signed to make sure 
// the user didn't spoof their identity 
func extractUser(req *http.Request) (string, error) {  
  userCookie, err := req.Cookie("identity")  
  if err != nil {    
    return "", err  
  }   
  return userCookie.Value, nil 
} 

func Middleware(h http.Handler) http.Handler {  
  return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {   
    user, err := extractUser(req)   
    if err != nil {    
      rw.WriteHeader(http.StatusUnauthorized)   
      rw.Write([]byte("unauthorized"))
      return       
    }      
    ctx := req.Context()    
    ctx = ContextWithUser(ctx, user)   
    req = req.WithContext(ctx)   
    h.ServeHTTP(rw, req)  
  }) 
}
```

In the middleware, you first get your user value. Next, you extract the context from the request with the Context method and create a new context that contains the user with your ContextWithUser function. It is idiomatic to reuse the ctx variable name when you wrap a context. You then make a new request from the old request and the new context by using the WithContext method. Finally, you call the next function in your handler chain with our new request and the supplied http.ResponseWriter.

In most cases, you want to extract the value from the context in your request handler and pass it in to your business logic explicitly.

```go
func (c Controller) DoLogic(rw http.ResponseWriter, req *http.Request) {  
  ctx := req.Context()  
  user, ok := identity.UserFromContext(ctx)  // identity is another package, for more info, see ch14/sample_code/context_user
  if !ok {   
    rw.WriteHeader(http.StatusInternalServerError) 
    return    
  }    
  data := req.URL.Query().Get("data")  
  result, err := c.Logic.BusinessLogic(ctx, user, data)  
  if err != nil {     
    rw.WriteHeader(http.StatusInternalServerError)   
    rw.Write([]byte(err.Error()))   
    return   
  } 
  rw.Write([]byte(result)) 
}
```

In some situations, it’s better to keep a value in the context. This information is meant for management of your application; it is not part of your business state. Here is a simple context-aware GUID implementation that tracks from service to service and creates logs with the GUID included:

```go
package tracker

import (
	"context"
	"fmt"
	"net/http"

	"github.com/google/uuid"
)

type guidKey int

const key guidKey = 1

func contextWithGUID(ctx context.Context, guid string) context.Context {
	return context.WithValue(ctx, key, guid)
}

func guidFromContext(ctx context.Context) (string, bool) {
	g, ok := ctx.Value(key).(string)
	return g, ok
}

func Middleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		ctx := req.Context()
		if guid := req.Header.Get("X-GUID"); guid != "" {
			ctx = contextWithGUID(ctx, guid)
		} else {
			ctx = contextWithGUID(ctx, uuid.New().String())
		}
		req = req.WithContext(ctx)
		h.ServeHTTP(rw, req)
	})
}

type Logger struct{}

func (Logger) Log(ctx context.Context, message string) {
	if guid, ok := guidFromContext(ctx); ok {
		message = fmt.Sprintf("GUID: %s - %s", guid, message)
	}
	// do logging
	fmt.Println(message)
}

func Request(req *http.Request) *http.Request {
	ctx := req.Context()
	if guid, ok := guidFromContext(ctx); ok {
		req.Header.Add("X-GUID", guid)
	}
	return req
}
```

The Request function is used when this service makes a call to another service. It takes in an *http.Request, adds a header with the GUID if it exists in the context, and returns the *http.Request.

The business logic is completely unaware of any tracking information:

```go
type Logger interface {   
  Log(context.Context, string)
} 

type RequestDecorator func(*http.Request) *http.Request

type LogicImpl struct {   
  RequestDecorator RequestDecorator  
  Logger           Logger  
  Remote           string 
}

func (l LogicImpl) Process(ctx context.Context, data string) (string, error) {    
  l.Logger.Log(ctx, "starting Process with "+data)   
  req, err := http.NewRequestWithContext(ctx, http.MethodGet, l.Remote+"/second?query="+data, nil)    
  if err != nil {    
    l.Logger.Log(ctx, "error building remote request:"+err.Error())  
    return "", err   
  }   
  req = l.RequestDecorator(req)
  resp, err := http.DefaultClient.Do(req)   
  // process the response, for more info, see ch14/sample_code/context_guid
}
```

The GUID is passed through to the logger and the request decorator without the business logic being aware of it, separating the data needed for program logic from the data needed for program management. The only place that’s aware of the association is the code in `main` that wires up your dependencies:

```go
controller := Controller{   
  Logic: LogicImpl{   
    RequestDecorator: tracker.Request,    
    Logger:           tracker.Logger{},    
    Remote:           "http://localhost:4000",    
  }, 
}
```

### Cancellation

While context values are useful for passing metadata and working around the limita‐tions of Go’s HTTP API, the context has a second use. The context also allows you to control the responsiveness of your application and coordinate concurrent goroutines.

Imagine that you have a request that launches several goroutines, each one calling a different HTTP service. If one service returns an error that prevents you from return‐ing a valid result, there is no point in continuing to process the other goroutines. In Go, this is called **cancellation**, and the context provides the mechanism for its implementation.

To create a cancellable context, use the context.WithCancel function. It takes in a context.Context as a parameter and returns a context.Context and a context.CancelFunc. Just like context.WithValue, the returned context.Context is a child context of the context that was passed into the function. A context.Cancel Func is a function that takes no parameters and cancels the context, telling all the code that’s listening for potential cancellation that it’s time to stop processing.

Anytime you create a context that has an associated cancel function, you must call that cancel function when you are done processing, whether or not your processing ends in an error. If you do not, your program will leak resources (memory and goroutines) and eventually slow down or crash. No error occurs if you call the cancel function more than once; any invocation after the first does nothing.

The easiest way to make sure you call the cancel function is to use defer to invoke it right after the cancel function is returned.

This leads to the question, how do you detect cancellation? The context.Context interface has a method called Done. It returns a channel of type struct{}. (The reason this is the chosen return type is that an empty struct uses no memory.) This channel is closed when the cancel function is invoked. Remember, a closed channel always immediately returns its zero value when you attempt to read it.

```go
func makeRequest(ctx context.Context, url string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	return http.DefaultClient.Do(req)
}

func main() {
	ctx, cancelFunc := context.WithCancel(context.Background())
	defer cancelFunc()
	ch := make(chan string)
	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		defer wg.Done()
		for {
			resp, err := makeRequest(ctx, "http://httpbin.org/status/200,200,200,500")
			if err != nil {
				fmt.Println("error in status goroutine:", err)
				cancelFunc()
				return
			}
			if resp.StatusCode == http.StatusInternalServerError {
				fmt.Println("bad status, exiting")
				cancelFunc()
				return
			}
			select {
			case ch <- "success from status":
			case <-ctx.Done():
			}
			time.Sleep(1 * time.Second)
		}
	}()
	go func() {
		defer wg.Done()
		for {
			resp, err := makeRequest(ctx, "http://httpbin.org/delay/1")
			if err != nil {
				fmt.Println("error in delay goroutine:", err)
				cancelFunc()
				return
			}
			select {
			case ch <- "success from delay: " + resp.Header.Get("date"):
			case <-ctx.Done():
			}
		}
	}()
loop:
	for {
		select {
		case s := <-ch:
			fmt.Println("in main:", s)
		case <-ctx.Done():
			fmt.Println("in main: cancelled!")
			break loop
		}
	}
	wg.Wait()
}

/*
in main: success from status
in main: success from delay: Sat, 02 Nov 2024 07:27:05 GMT
in main: success from status
in main: success from status
in main: success from delay: Sat, 02 Nov 2024 07:27:06 GMT
in main: success from status
in main: success from delay: Sat, 02 Nov 2024 07:27:08 GMT
in main: success from delay: Sat, 02 Nov 2024 07:27:09 GMT
bad status, exiting
in main: cancelled!
error in delay goroutine: Get "http://httpbin.org/delay/1": context canceled
*/
```

There are some interesting things to note. First, you are calling cancelFunc multiple times. As mentioned earlier, this is perfectly fine and causes no problems. Next, notice that you got an error from the delay goroutine after cancellation was triggered. This is because the built-in HTTP client in the Go standard library respects cancella‐tion. You created the request using the cancellable context, and when it was cancelled, the request ended. This triggers the error path in the goroutine and makes sure that it does not leak.

You might wonder about the error that caused the cancellation and how you can report it. An alternate version of WithCancel, called WithCancelCause, returns a cancellation function that takes in an error as a parameter. The Cause function in the context package returns the error that was passed into the first invocation of the cancellation function.

```go
func makeRequest(ctx context.Context, url string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	return http.DefaultClient.Do(req)
}

func main() {
	ctx, cancelFunc := context.WithCancelCause(context.Background())
	defer cancelFunc(nil)
	ch := make(chan string)
	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		defer wg.Done()
		for {
			resp, err := makeRequest(ctx, "http://httpbin.org/status/200,200,200,500")
			if err != nil {
				cancelFunc(fmt.Errorf("in status goroutine: %w", err))
				return
			}
			if resp.StatusCode == http.StatusInternalServerError {
				cancelFunc(errors.New("bad status"))
				return
			}
			ch <- "success from status"
			time.Sleep(1 * time.Second)
		}
	}()
	go func() {
		defer wg.Done()
		for {
			resp, err := makeRequest(ctx, "http://httpbin.org/delay/1")
			if err != nil {
				fmt.Println("in delay goroutine:", err)
				cancelFunc(fmt.Errorf("in delay goroutine: %w", err))
				return
			}
			ch <- "success from delay: " + resp.Header.Get("date")
		}
	}()
loop:
	for {
		select {
		case s := <-ch:
			fmt.Println("in main:", s)
		case <-ctx.Done():
			fmt.Println("in main: cancelled with error", context.Cause(ctx))
			break loop
		}
	}
	wg.Wait()
	fmt.Println("context cause:", context.Cause(ctx))
}

/*
in main: success from status
in main: success from delay: Sat, 02 Nov 2024 07:49:41 GMT
in main: success from status
in main: success from delay: Sat, 02 Nov 2024 07:49:42 GMT
in main: success from status
in main: success from delay: Sat, 02 Nov 2024 07:49:44 GMT
in main: success from status
in main: success from delay: Sat, 02 Nov 2024 07:49:46 GMT
in main: success from delay: Sat, 02 Nov 2024 07:49:47 GMT
in main: cancelled with error bad status
in delay goroutine: Get "http://httpbin.org/delay/1": context canceled
context cause: bad status
*/
```

You see that the error from the status goroutine is printed out both when cancellation is initially detected in the switch statement and after you finish waiting for the delay goroutine to complete. Notice that the delay goroutine called cancelFunc with an error, but that error doesn’t overwrite the initial cancellation error.

### Contexts with Deadlines

Generally, a server can do four things to manage its load: 

- Limit simultaneous requests 
- Limit the number of queued requests waiting to run 
- Limit the amount of time a request can run 
- Limit the resources a request can use (such as memory or disk space) 

Go provides tools to handle the first three. You saw how to handle the first two when learning about concurrency in Chapter 12 (Concurrency in Go). By limiting the number of goroutines, a server manages simultaneous load. The size of the waiting queue is handled via buffered channels.

The context provides a way to control how long a request runs. When building an application, you should have an idea of your performance envelope: how long you have for your request to complete before the user has an unsatisfactory experience. If you know the maximum amount of time that a request can run, you can enforce it using the context.

You can use one of two functions to create a time-limited context. The first is `context.WithTimeout`. The second function is `context.WithDeadline`.

If you want to find out when a context will automatically cancel, use the Deadline method on context.Context. It returns a time.Time that indicates the time and a bool that indicates if a timeout was set.

When you set a time limit for the overall duration of the request, you might want to subdivide that time. And if you call another service from your service, you might want to limit how long you allow the network call to run, reserving some time for the rest of your processing or for other network calls. You control how long an individual call takes by creating a child context that wraps a parent context by using context.WithTimeout or context.WithDeadline.

Any timeout that you set on the child context is bounded by the timeout set on the parent context; if a parent context times out in 2 seconds, you can declare that a child context times out in 3 seconds, but when the parent context times out after 2 seconds, so will the child.

```go
func main() {
	ctx := context.Background()
	parent, cancel := context.WithTimeout(ctx, 2*time.Second)
	defer cancel()
	child, cancel2 := context.WithTimeout(parent, 3*time.Second)
	defer cancel2()
	start := time.Now()
	<-child.Done()
	end := time.Now()
	fmt.Println(end.Sub(start).Truncate(time.Second)) // 2s
}
```

In this sample, you specify a 2-second timeout on the parent context and a 3-second timeout on the child context. You then wait for the child context to complete by wait‐ing on the channel returned from the Done method on the child context.Context.

Since contexts with timers can cancel because of a timeout or an explicit call to the cancellation function, the context API provides a way to tell what caused cancellation. The `Err` method returns nil if the context is still active, or it returns one of two sentinel errors if the context has been canceled: `context.Canceled` or `context.DeadlineExceeded`. The first is returned after explicit cancellation, and the second is returned when a timeout triggered cancellation.

Let’s see them in use. You’re going to make one more change to your httpbin pro‐gram. This time, you’re adding a timeout to the context that’s used to control how long the goroutines run:

```go
ctx, cancelFuncParent := context.WithTimeout(context.Background(), 3*time.Second) 
defer cancelFuncParent() 
ctx, cancelFunc := context.WithCancelCause(ctx) 
defer cancelFunc(nil)
```

The complete code is here: 

```go
func makeRequest(ctx context.Context, url string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	return http.DefaultClient.Do(req)
}

func main() {
	ctx, cancelFuncParent := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancelFuncParent()
	ctx, cancelFunc := context.WithCancelCause(ctx)
	defer cancelFunc(nil)
	ch := make(chan string)
	var wg sync.WaitGroup
	wg.Add(2)
	go func() {
		defer wg.Done()
		for {
			resp, err := makeRequest(ctx, "http://httpbin.org/status/200,200,200,500")
			if err != nil {
				cancelFunc(fmt.Errorf("in status goroutine: %w", err))
				return
			}
			if resp.StatusCode == http.StatusInternalServerError {
				cancelFunc(errors.New("bad status"))
				return
			}
			ch <- "success from status"
			time.Sleep(1 * time.Second)
		}
	}()
	go func() {
		defer wg.Done()
		for {
			resp, err := makeRequest(ctx, "http://httpbin.org/delay/1")
			if err != nil {
				fmt.Println("in delay goroutine:", err)
				cancelFunc(fmt.Errorf("in delay goroutine: %w", err))
				return
			}
			ch <- "success from delay: " + resp.Header.Get("date")
		}
	}()
loop:
	for {
		select {
		case s := <-ch:
			fmt.Println("in main:", s)
		case <-ctx.Done():
			fmt.Println("in main: cancelled with cause:", context.Cause(ctx), "err:", ctx.Err())
			break loop
		}
	}
	wg.Wait()
	fmt.Println("context cause:", context.Cause(ctx))
}
```

The results are random:

```go
/*
in main: success from status
in main: cancelled with cause: context deadline exceeded err: context deadline exceeded
in delay goroutine: Get "http://httpbin.org/delay/1": context deadline exceeded
context cause: context deadline exceeded
*/
```

Notice that the error returned by context.Cause is the same error that’s returned by the Err method: context.DeadlineExceeded.

```go
/*
in main: cancelled with cause: bad status err: context canceled
in delay goroutine: Get "http://httpbin.org/delay/1": context canceled
context cause: bad status
*/
```

Now the error returned by context.Cause is bad status, but Err returns a context.Canceled error.

### Context Cancellation in Your Own Code

Most of the time, you don’t need to worry about timeouts or cancellation within your own code; it simply doesn’t run for long enough. Whenever you call another HTTP service or the database, you should pass along the context; those libraries properly handle cancellation via the context.

You should think about handling cancellation for two situations. The first is when you have a function that reads or writes channels by using a select statement. As shown in “Cancellation” on page 358, include a case that checks the channel returned by the Done method on the context. This allows your function to exit upon context cancellation, even if the goroutines do not handle cancellation properly.

The second situation is when you write code that runs long enough that it should be interrupted by a context cancellation. In that case, check the status of the context periodically using context.Cause. The context.Cause function returns an error if the context has been cancelled.

```go
func longRunningComputation(ctx context.Context, data string) (string, error) {   
  for {      
    // do some processing  
    // insert this if statement periodically  
    // to check if the context has been cancelled   
    if err := context.Cause(ctx); err != nil {     
      // return a partial value if it makes sense,  
      // or a default one if it doesn't      
      return "", err      
    }      
    // do some more processing and loop again  
  }
}
```

Here’s an example loop from a function that calculates π by using the inefficient Leibniz algorithm. Using context cancellation allows you to control how long it can run:

```go
func main() {
	calcWithTimeout(1)
	calcWithTimeout(2)
	calcWithTimeout(5)
	calcWithTimeout(10)
}

func calcWithTimeout(numSeconds time.Duration) {
	ctx, cancelFunc := context.WithTimeout(context.Background(), numSeconds*time.Second)
	defer cancelFunc()
	start := time.Now()
	result, err := calcPi(ctx)
	calcTime := time.Since(start)
	fmt.Println(result)
	fmt.Println(calcTime)
	fmt.Println(err)
}

func calcPi(ctx context.Context) (string, error) {
	var sum big.Float
	sum.SetInt64(0)
	var d big.Float
	d.SetInt64(1)
	two := big.NewFloat(2)
	i := 0
	for {
		if err := context.Cause(ctx); err != nil {
			fmt.Println("cancelled after", i, "iterations")
			return sum.Text('g', 100), err
		}
		var diff big.Float
		diff.SetInt64(4)
		diff.Quo(&diff, &d)
		if i%2 == 0 {
			sum.Add(&sum, &diff)
		} else {
			sum.Sub(&sum, &diff)
		}
		d.Add(&d, two)
		i++
	}
}

/*
cancelled after 4890501 iterations
3.1415928580678211426251145166332889857585541903972625732421875
1.001058042s
context deadline exceeded
cancelled after 10222415 iterations
3.14159275141403517201711681483544680304476059973239898681640625
2.001050083s
context deadline exceeded
cancelled after 25507137 iterations
3.14159269279450687503522920973608734129811637103557586669921875
5.001026625s
context deadline exceeded
cancelled after 51019165 iterations
3.14159267319027100929217100055979017270146869122982025146484375
10.001053834s
context deadline exceeded
*/
```

